apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_DATA@microservice-auth-config}
  namespace: ${NAMESPACE@microservice-config}
  labels:
    moduleid: microservice-auth-data
    version: 1.70.0-master
spec:
  clusterIP: None
  ports:
    -
      port: ${INTERNAL_PORT_DATA@microservice-auth-config}
      targetPort: ${INTERNAL_PORT_DATA@microservice-auth-config}
  selector:
    app: ${STATEFUL_DATA@microservice-auth-config}
