apiVersion: v1
kind: Service
metadata:
  name: microservice-auth-data
  namespace: ${NAMESPACE@microservice-config}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: microservice-auth-data-set
