apiVersion: v1
kind: Service
metadata:
  name: microservice-auth-data
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-data
    version: 1.70.1-auth-stateful-prod
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    role: microservice-auth-data-set
