apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: '${STATEFUL_DATA@microservice-auth-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-data
    version: 1.70.1-auth-base-cache-data-prod
spec:
  serviceName: '${SERVICE_DATA@microservice-auth-config}'
  selector:
    matchLabels:
      app: '${STATEFUL_DATA@microservice-auth-config}'
  replicas: 1
  template:
    metadata:
      labels:
        moduleid: microservice-auth-data
        version: 1.70.1-auth-base-cache-data-prod
        app: '${STATEFUL_DATA@microservice-auth-config}'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        -
          name: data
          image: 'mongo:latest'
          command:
            - mongod
            - '--bind_ip_all'
          ports:
            -
              containerPort: '${INTERNAL_PORT_DATA@microservice-auth-config}'
          volumeMounts:
            -
              name: microservice-auth-data-storage
              mountPath: /data/db
  volumeClaimTemplates:
    -
      metadata:
        name: microservice-auth-data-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi
